In [131]:
import pandas as pd
df= pd.read_csv(r"C:\Users\Marko\Desktop\data_folder\steam_games\games_march2025_cleaned.csv")

In [2]:
df

,appid,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,...,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent
0,730,Counter-Strike 2,2012-08-21,0,0.00,1,"For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...",NaN,...,879,5174,350,0,1212356,"{'FPS': 90857, 'Shooter': 65397, 'Multiplayer'...",86,8632939,82,96473
1,578080,PUBG: BATTLEGROUNDS,2017-12-21,0,0.00,0,"LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...","LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...",Play PUBG: BATTLEGROUNDS for free. Land on str...,NaN,...,0,0,0,0,616738,"{'Survival': 14838, 'Shooter': 12727, 'Battle ...",59,2513842,68,16720
2,570,Dota 2,2013-07-09,0,0.00,2,"The most-played game on Steam. Every day, mill...","The most-played game on Steam. Every day, mill...","Every day, millions of players worldwide enter...",“A modern multiplayer masterpiece.” 9.5/10 – D...,...,1536,898,892,0,555977,"{'Free to Play': 59933, 'MOBA': 20158, 'Multip...",81,2452595,80,29366
3,271590,Grand Theft Auto V Legacy,2015-04-13,17,0.00,0,"When a young street hustler, a retired bank ro...","When a young street hustler, a retired bank ro...",Grand Theft Auto V for PC offers players the o...,NaN,...,771,7101,74,0,117698,"{'Open World': 32644, 'Action': 23539, 'Multip...",87,1803832,92,17517
4,359550,Tom Clancy's Rainbow Six® Siege,2015-12-01,17,3.99,9,Edition Comparison Ultimate Edition The Tom Cl...,“One of the best first-person shooters ever ma...,"Tom Clancy's Rainbow Six® Siege is an elite, t...",NaN,...,682,2434,306,80,89916,"{'FPS': 9831, 'PvP': 9162, 'e-sports': 9072, '...",84,1168020,76,12608
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89613,2115110,Outrun Them,2024-02-29,0,3.99,0,The name of the game is literally the game. Ou...,The name of the game is literally the game. Ou...,It's all in the name.. outrun them.,NaN,...,0,0,0,0,0,"{'2D Platformer': 91, 'Runner': 85, 'Platforme...",-1,-1,-1,-1
89614,1174200,Lands of Pharaoh: Episode 1,2020-01-07,0,10.00,0,Join Our Discord Channel About the Game Briefl...,Briefly: Lands of Pharaoh is a third person vi...,Lands of Pharaoh is a multi-camera-angle based...,NaN,...,0,0,0,0,0,"{'Action': 43, 'Adventure': 41, 'Indie': 41, '...",-1,-1,-1,-1
89615,1160190,Player One,2019-10-10,0,1.99,0,Player One is a new 3D game where you take con...,Player One is a new 3D game where you take con...,"3D Game, Thirdperson Platformer",NaN,...,0,0,0,0,0,"{'Indie': 31, 'Early Access': 21}",-1,-1,-1,-1
89616,3380340,DragonRoad,2025-01-25,0,29.99,0,"This is an open world game on 3D, also a m...","This is an open world game on 3D, also a m...","This is an open world game on 3D, Also a missi...",NaN,...,0,0,0,0,0,"{'RPG': 117, 'Action-Adventure': 111, 'Strateg...",-1,-1,-1,-1
89617,763730,Ragtag Adventurers,2018-03-01,0,9.99,0,Ragtag Adventurers is a Boss Rush game that pi...,Ragtag Adventurers is a Boss Rush game that pi...,Ragtag Adventurers is a boss rush game that pi...,NaN,...,0,0,0,0,0,"{'Action': 22, 'Indie': 21}",-1,-1,-1,-1

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89618 entries, 0 to 89617
Data columns (total 47 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   appid                     89618 non-null  int64
 1   name                      89618 non-null  object
 2   release_date              89618 non-null  object
 3   required_age              89618 non-null  int64
 4   price                     89618 non-null  float64
 5   dlc_count                 89618 non-null  int64
 6   detailed_description      89421 non-null  object
 7   about_the_game            89398 non-null  object
 8   short_description         89498 non-null  object
 9   reviews                   10401 non-null  object
 10  header_image              89618 non-null  object
 11  website                   41114 non-null  object
 12  support_url               44110 non-null  object
 13  support_email             78798 non-null  object
 14  windows                   89618 non-null  bool
 15  mac                       89618 non-null  bool
 16  linux                     89618 non-null  bool
 17  metacritic_score          89618 non-null  int64
 18  metacritic_url            3547 non-null   object
 19  achievements              89618 non-null  int64
 20  recommendations           89618 non-null  int64
 21  notes                     16643 non-null  object
 22  supported_languages       89618 non-null  object
 23  full_audio_languages      89618 non-null  object
 24  packages                  89618 non-null  object
 25  developers                89618 non-null  object
 26  publishers                89618 non-null  object
 27  categories                89618 non-null  object
 28  genres                    89618 non-null  object
 29  screenshots               89618 non-null  object
 30  movies                    89618 non-null  object
 31  user_score                89618 non-null  int64
 32  score_rank                39 non-null     float64
 33  positive                  89618 non-null  int64
 34  negative                  89618 non-null  int64
 35  estimated_owners          89618 non-null  object
 36  average_playtime_forever  89618 non-null  int64
 37  average_playtime_2weeks   89618 non-null  int64
 38  median_playtime_forever   89618 non-null  int64
 39  median_playtime_2weeks    89618 non-null  int64
 40  discount                  89618 non-null  int64
 41  peak_ccu                  89618 non-null  int64
 42  tags                      89618 non-null  object
 43  pct_pos_total             89618 non-null  int64
 44  num_reviews_total         89618 non-null  int64
 45  pct_pos_recent            89618 non-null  int64
 46  num_reviews_recent        89618 non-null  int64
dtypes: bool(3), float64(2), int64(19), object(23)
memory usage: 30.3+ MB

In [23]:
df['name'].head(20)

0                    Counter-Strike 2
1                 PUBG: BATTLEGROUNDS
2                              Dota 2
3           Grand Theft Auto V Legacy
4     Tom Clancy's Rainbow Six® Siege
5                     Team Fortress 2
6                            Terraria
7                                Rust
8                         Garry's Mod
9                       Apex Legends™
10                 Black Myth: Wukong
11           The Witcher 3: Wild Hunt
12                         ELDEN RING
13                     Stardew Valley
14                     Cyberpunk 2077
15                      HELLDIVERS™ 2
16                    Baldur's Gate 3
17             Euro Truck Simulator 2
18              Red Dead Redemption 2
19                          Destiny 2
Name: name, dtype: object

In [25]:
df[['name', 'price']]

                                  name  price
0                     Counter-Strike 2   0.00
1                  PUBG: BATTLEGROUNDS   0.00
2                               Dota 2   0.00
3            Grand Theft Auto V Legacy   0.00
4      Tom Clancy's Rainbow Six® Siege   3.99
...                                ...    ...
89613                      Outrun Them   3.99
89614      Lands of Pharaoh: Episode 1  10.00
89615                       Player One   1.99
89616                       DragonRoad  29.99
89617               Ragtag Adventurers   9.99

[89618 rows x 2 columns]

In [ ]:
#Ispiši podatke o Geometry Dashu (index = 35)
df.iloc[35]

appid                                                                                                              322170
name                                                                                                        Geometry Dash
release_date                                                                                                   2014-12-22
required_age                                                                                                            0
price                                                                                                                4.99
                                                                     ...
tags                  {'Difficult': 3733, 'Music': 2945, 'Level Editor': 2851, 'Great Soundtrack': 2818, 'Precision Pl...
pct_pos_total                                                                                                          93
num_reviews_total                                                                                                  370690
pct_pos_recent                                                                                                         91
num_reviews_recent                                                                                                   6137
Name: 35, Length: 47, dtype: object

In [ ]:
#Ispiši cijenu(index stupca) od Terrarije (index retka 6) i GD (index retka 35)
df.iloc[[6,35],4]

6     9.99
35    4.99
Name: price, dtype: float64

In [29]:
df.columns

Index(['appid', 'name', 'release_date', 'required_age', 'price', 'dlc_count',
       'detailed_description', 'about_the_game', 'short_description',
       'reviews', 'header_image', 'website', 'support_url', 'support_email',
       'windows', 'mac', 'linux', 'metacritic_score', 'metacritic_url',
       'achievements', 'recommendations', 'notes', 'supported_languages',
       'full_audio_languages', 'packages', 'developers', 'publishers',
       'categories', 'genres', 'screenshots', 'movies', 'user_score',
       'score_rank', 'positive', 'negative', 'estimated_owners',
       'average_playtime_forever', 'average_playtime_2weeks',
       'median_playtime_forever', 'median_playtime_2weeks', 'discount',
       'peak_ccu', 'tags', 'pct_pos_total', 'num_reviews_total',
       'pct_pos_recent', 'num_reviews_recent'],
      dtype='object')

In [ ]:
#Razlika između genres i tags
df.genres
df.tags

0                                              ['Action', 'Free To Play']
1        ['Action', 'Adventure', 'Massively Multiplayer', 'Free To Play']
2                                  ['Action', 'Strategy', 'Free To Play']
3                                                 ['Action', 'Adventure']
4                                                              ['Action']
                                       ...
89613                                           ['Indie', 'Early Access']
89614                        ['Action', 'Adventure', 'Indie', 'Strategy']
89615                                           ['Indie', 'Early Access']
89616                      ['Adventure', 'RPG', 'Simulation', 'Strategy']
89617                                                 ['Action', 'Indie']
Name: genres, Length: 89618, dtype: object

Provjeri jesu li genrovi pravilno dodijeljeni igrama kao i user-defined tags

In [33]:
df['genres'].value_counts()

genres
['Casual', 'Indie']                                                       5099
['Action', 'Indie']                                                       4692
['Action', 'Adventure', 'Indie']                                          4103
['Adventure', 'Indie']                                                    3432
['Adventure', 'Casual', 'Indie']                                          2881
                                                                          ...
['Indie', 'Utilities', 'Video Production']                                   1
['Violent', 'Adventure', 'Indie', 'Early Access']                            1
['Audio Production', 'Photo Editing', 'Utilities', 'Video Production']       1
['Action', 'Adventure', 'Casual', 'Sports', 'Strategy']                      1
['Gore', 'Action', 'Early Access']                                           1
Name: count, Length: 2689, dtype: int64

In [34]:
df['tags'].value_counts()

tags
[]                                                                                                                                                                                                                                                                                                                                                                                                           16872
{'Indie': 21, 'Casual': 21}                                                                                                                                                                                                                                                                                                                                                                                    109
{'Adventure': 21, 'Casual': 21, 'Hidden Object': 6}                                                                                                                                                                                                                                                                                                                                                             97
{'Action': 21, 'Indie': 21}                                                                                                                                                                                                                                                                                                                                                                                     94
{'Action': 21, 'Indie': 21, 'Casual': 21}                                                                                                                                                                                                                                                                                                                                                                       92
                                                                                                                                                                                                                                                                                                                                                                                                             ...
{'Casual': 22, 'Action': 21, 'Indie': 21, 'Racing': 20}                                                                                                                                                                                                                                                                                                                                                          1
{'Adventure': 213, 'Action': 208, 'Strategy': 183, 'Action-Adventure': 179, 'Strategy RPG': 172, 'Choose Your Own Adventure': 162, 'Third-Person Shooter': 156, 'Top-Down': 149, 'Third Person': 140, 'Crafting': 131, 'Nature': 120, 'Survival': 118, 'Building': 105, 'Zombies': 91, 'Character Customization': 76, 'Base-Building': 60, 'Singleplayer': 43, 'Fishing': 27, 'Farming': 25, 'Indie': 21}        1
{'2D Platformer': 111, 'Retro': 105, 'Cute': 102, 'Platformer': 99, 'Shooter': 94, 'Action': 87, 'Casual': 85, 'Indie': 83, 'Gore': 79, 'Violent': 73, 'Pixel Graphics': 67, 'Singleplayer': 63, '2D': 61, 'Cartoony': 59, 'Colorful': 53, 'Old School': 46, 'Family Friendly': 41, 'Robots': 37, 'Difficult': 32, 'Addictive': 27}                                                                              1
{'Survival': 196, 'Zombies': 190, 'Open World': 187, 'Post-apocalyptic': 184, 'Multiplayer': 181, 'RPG': 175, 'Indie': 173, 'Base-Building': 171, 'Open World Survival Craft': 170, 'Exploration': 163, 'Crafting': 161, 'Horror': 159, 'Action RPG': 157, 'Loot': 155, 'Survival Horror': 153, 'Early Access': 152, 'Simulation': 149, 'Online Co-Op': 133, 'First-Person': 131, 'Third Person': 129}           1
{'Psychological Horror': 75, 'Walking Simulator': 69, 'Horror': 66, 'Adventure': 63, 'First-Person': 41, 'Dark': 35, "1990's": 33, '1980s': 31, 'Realistic': 29, 'Psychological': 27, 'Atmospheric': 25, 'Mystery': 23, '3D': 21, 'Singleplayer': 19, 'Supernatural': 17}                                                                                                                                        1
Name: count, Length: 70420, dtype: int64

Zaključak: Većina igri nema definirane tagove, ali za definirane se podudaraju uz dodatak: hidden object

In [39]:
df.loc[0:7,'name':'price']

                              name release_date  required_age  price
0                 Counter-Strike 2   2012-08-21             0   0.00
1              PUBG: BATTLEGROUNDS   2017-12-21             0   0.00
2                           Dota 2   2013-07-09             0   0.00
3        Grand Theft Auto V Legacy   2015-04-13            17   0.00
4  Tom Clancy's Rainbow Six® Siege   2015-12-01            17   3.99
5                  Team Fortress 2   2007-10-10             0   0.00
6                         Terraria   2011-05-16             0   9.99
7                             Rust   2018-02-08             0  39.99

In [ ]:
#Ispis prvih 30 igrica sa nazivom i cijenom
pd.set_option('display.max_rows',30)
df[['name','price']].head(30)

                               name  price
0                  Counter-Strike 2   0.00
1               PUBG: BATTLEGROUNDS   0.00
2                            Dota 2   0.00
3         Grand Theft Auto V Legacy   0.00
4   Tom Clancy's Rainbow Six® Siege   3.99
5                   Team Fortress 2   0.00
6                          Terraria   9.99
7                              Rust  39.99
8                       Garry's Mod   5.99
9                     Apex Legends™   0.00
10               Black Myth: Wukong  59.99
11         The Witcher 3: Wild Hunt  39.99
12                       ELDEN RING  59.99
13                   Stardew Valley  14.99
14                   Cyberpunk 2077  59.99
15                    HELLDIVERS™ 2  39.99
16                  Baldur's Gate 3  59.99
17           Euro Truck Simulator 2  19.99
18            Red Dead Redemption 2  59.99
19                        Destiny 2   0.00
20                     Phasmophobia  19.99
21                         Among Us   2.99
22                         Warframe   0.00
23                      War Thunder   0.00
24                 Dead by Daylight  19.99
25                         Unturned   0.00
26            ARK: Survival Evolved  14.99
27                       The Forest  19.99
28                        Fall Guys   0.00
29                         PAYDAY 2   9.99

Analiza koliko igri je za koji OS

In [57]:
df['windows'].value_counts()

windows
True     89588
False       30
Name: count, dtype: int64

In [58]:
df['linux'].value_counts()

linux
False    76991
True     12627
Name: count, dtype: int64

In [59]:
df['mac'].value_counts()

mac
False    72180
True     17438
Name: count, dtype: int64

In [60]:
df['supported_languages'].value_counts()

supported_languages
['English']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           44652
['English', 'Russian']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 2267
['Simplified Chinese']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1944
['English', 'Simplified Chinese']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1847
['English', 'Japanese']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1674
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ...
['English', 'French', 'German', 'Spanish - Spain', 'Russian', 'Turkish', 'Japanese', 'Thai', 'Simplified Chinese', 'Traditional Chinese', 'Portuguese - Portugal', 'Vietnamese', 'Korean']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
['English', 'Portuguese - Brazil', 'French', 'Italian', 'German', 'Spanish - Spain', 'Japanese']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
['English', 'French', 'Italian', 'German', 'Spanish - Spain', 'Japanese', 'Korean', 'Portuguese - Brazil', 'Russian', 'Simplified Chinese', 'Traditional Chinese', 'Spanish - Latin America', 'Arabic', 'Bulgarian', 'Czech', 'Danish', 'Dutch', 'Finnish', 'Greek', 'Hungarian', 'Norwegian', 'Polish', 'Portuguese - Portugal', 'Romanian', 'Swedish', 'Thai', 'Turkish', 'Ukrainian', 'Vietnamese', 'Indonesian', 'Afrikaans', 'Albanian', 'Amharic', 'Armenian', 'Assamese', 'Azerbaijani', 'Bangla', 'Basque', 'Belarusian', 'Bosnian', 'Catalan', 'Cherokee', 'Croatian', 'Dari', 'Estonian', 'Filipino', 'Galician', 'Georgian', 'Gujarati', 'Hausa', 'Hebrew', 'Hindi', 'Icelandic', 'Igbo', 'Irish', "K'iche'", 'Kannada', 'Kazakh', 'Khmer', 'Kinyarwanda', 'Konkani', 'Kyrgyz', 'Latvian', 'Lithuanian', 'Luxembourgish', 'Macedonian', 'Malay', 'Malayalam', 'Maltese', 'Maori', 'Marathi', 'Mongolian', 'Nepali', 'Odia', 'Persian', 'Punjabi (Gurmukhi)', 'Punjabi (Shahmukhi)', 'Quechua', 'Scots', 'Serbian', 'Sindhi', 'Sinhala', 'Slovak', 'Slovenian', 'Sorani', 'Sotho', 'Swahili', 'Tajik', 'Tamil', 'Tatar', 'Telugu', 'Tigrinya', 'Tswana', 'Turkmen', 'Urdu', 'Uyghur', 'Uzbek', 'Valencian', 'Welsh', 'Wolof', 'Xhosa', 'Yoruba', 'Zulu']        1
['English', 'French', 'German', 'Spanish - Spain', 'Traditional Chinese', 'Simplified Chinese', 'Japanese', 'Dutch', 'Portuguese - Portugal', 'Russian', 'Swedish', 'Turkish']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
['English', 'Italian', 'Spanish - Spain', 'Polish']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1
Name: count, Length: 14560, dtype: int64

In [104]:
#df.set_index('name', inplace=True)
df.loc['Terraria':'Warframe']

,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,header_image,website,...,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent
name,,,,,,,,,,,,,,,,,,,,,
Terraria,2011-05-16,0,9.99,2,"Dig, Fight, Explore, Build: The very world is at your fingertips as you fight for survival, fort...","Dig, Fight, Explore, Build: The very world is at your fingertips as you fight for survival, fort...","Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game. Four Pac...",NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/105600/header.jpg?t=1731252354,http://www.terraria.org/,...,0,0,0,0,30516,"{'Open World Survival Craft': 16365, 'Sandbox': 16065, 'Survival': 12778, '2D': 12602, 'Multipla...",97,1102434,96,8860
Rust,2018-02-08,0,39.99,4,"The only aim in Rust is to survive. Everything wants you to die - the island’s wildlife, other i...","The only aim in Rust is to survive. Everything wants you to die - the island’s wildlife, other i...","The only aim in Rust is to survive. Everything wants you to die - the island’s wildlife, other i...","“Rust is one of the cruelest games on Steam, and that's what makes it so compelling.” PC Gamer “...",https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/252490/header.jpg?t=1738927718,http://rust.facepunch.com/,...,836,3675,231,0,200902,"{'Survival': 18592, 'Crafting': 11822, 'Multiplayer': 11755, 'Open World': 11220, 'Open World Su...",87,993856,87,14960
Garry's Mod,2006-11-29,0,5.99,0,Garry's Mod is a physics sandbox. There aren't any predefined aims or goals. We give you the too...,Garry's Mod is a physics sandbox. There aren't any predefined aims or goals. We give you the too...,Garry's Mod is a physics sandbox. There aren't any predefined aims or goals. We give you the too...,"“It brings back the silly glee of unbridled experimentation, intuitive learning and playful soci...",https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/4000/header.jpg?t=1736937068,https://gmod.facepunch.com,...,100,1173,136,40,32384,"{'Sandbox': 18706, 'Moddable': 14479, 'Multiplayer': 14453, 'Physics': 14417, 'Building': 14389,...",96,985010,96,8277
Apex Legends™,2020-11-04,0,0.00,0,"Apex Legends: Takeover About the Game Conquer with character in Apex Legends, a free-to-play* He...","Conquer with character in Apex Legends, a free-to-play* Hero shooter where legendary characters ...","Apex Legends is the award-winning, free-to-play Hero Shooter from Respawn Entertainment. Master ...",“The champion of Battle Royales.” 9/10 – GameSpot “The best Battle Royale game.” 5/5 – GamesRada...,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1172470/header.jpg?t=1741192528,https://www.ea.com/games/apex-legends,...,548,667,211,0,151844,"{'Free to Play': 2170, 'Battle Royale': 1483, 'Multiplayer': 1477, 'FPS': 1442, 'Shooter': 1350,...",67,983230,53,7054
Black Myth: Wukong,2024-08-19,13,59.99,2,Digital Deluxe Edition The Black Myth: Wukong Digital Deluxe Edition includes: - Black Myth: Wuk...,Black Myth: Wukong is an action RPG rooted in Chinese mythology. The story is based on Journey t...,Black Myth: Wukong is an action RPG rooted in Chinese mythology. You shall set out as the Destin...,NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2358720/header.jpg?t=1739542141,https://www.heishenhua.com/,...,0,0,0,0,35990,"{'Mythology': 9421, 'Action RPG': 7720, 'Action': 7192, 'Souls-like': 6548, 'RPG': 6402, 'Combat...",96,825621,94,6139
The Witcher 3: Wild Hunt,2015-05-18,17,39.99,22,DISCOVER THE STORY BEFORE THE WITCHER IV About the Game One of the most acclaimed RPGs of all ti...,One of the most acclaimed RPGs of all time. Now ready for a new generation. You are Geralt of Ri...,"You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infeste...",“ONE OF THE BEST GAMES EVER MADE” 10/10 – GameSpot “AMAZING” 9.3/10 – IGN “ONE OF THE BEST RPGs ...,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/header.jpg?t=1736424367,https://www.thewitcher.com/witcher3,...,521,927,184,0,15129,"{'Open World': 12704, 'RPG': 10744, 'Story Rich': 9941, 'Atmospheric': 6852, 'Mature': 6780, 'Fa...",96,751939,95,4228
ELDEN RING,2022-02-24,16,59.99,2,ELDEN RING Shadow of the Erdtree Edition ELDEN RING Shadow of the Erdtree Edition includes: ELDE...,"THE CRITICALLY ACCLAIMED FANTASY ACTION RPG Rise, Tarnished, and be guided by grace to brandish ...","THE CRITICALLY ACCLAIMED FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish...",“Put a ring on it.” 10/10 – IGN “An unmissable open-world masterpiece.” 10/10 – Gaming Bible “Ex...,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/header.jpg?t=1739922037,NaN,...,1587,5675,464,0,46121,"{'Souls-like': 6823, 'Open World': 4941, 'Dark Fantasy': 4868, 'RPG': 4617, 'Difficult': 4500, '...",92,749606,93,6753
Stardew Valley,2016-02-26,0,14.99,1,Stardew Valley is an open-ended country-life RPG! You've inherited your grandfather's old farm p...,Stardew Valley is an open-ended country-life RPG! You've inherited your grandfather's old farm p...,You've inherited your grandfather's old farm plot in Stardew Valley. Armed with hand-me-down too...,"“Far more than just a farming game, this one-man labor of love is filled with seemingly endless ...",https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/header.jpg?t=1711128146,http://www.stardewvalley.net,...,158,2053,87,0,67309,"{'Farming Sim': 7706, 'Pixel Graphics': 7169, 'Multiplayer': 7088, 'Life Sim': 7083, 'RPG': 6396...",98,733626,98,8622
Cyberpunk 2077,2020-12-09,17,59.99,3,Cyberpunk 2077: Ultimate Edition Check out other games from CD PROJEKT RED About the Game Cyberp...,"Cyberpunk 2077 is an open-world, action-adventure RPG set in the megalopolis of Night City, wher...","Cyberpunk 2077 is an open-world, action-adventure RPG set in the dark future of Night City — a d...",NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/header.jpg?t=1734434803,https://www.cyberpunk.net,...,2657,3299,133,0,29239,"{'Cyberpunk': 6486, 'Open World': 5934, 'Nudity': 5144, 'RPG': 4938, 'Singleplayer': 4868, 'Sci-...",85,729016,96,7612
HELLDIVERS™ 2,2024-02-08,17,39.99,1,Digital Deluxe Edition Edition includes: ‘DP-53 Savior of the Free’ Armor Set. ‘Will of the Peop...,The Galaxy’s Last Line of Offence. Enlist in the Helldivers and join the fight for freedom acros...,The Galaxy’s Last Line of Offence. Enlist in the Helldivers and join the fight for freedom acros...,NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/553850/header.jpg?t=1741137570,NaN,...,0,0,0,0,48290,"{'Online Co-Op': 939, 'PvE': 827, 'Third-Person Shooter': 821, 'Multiplayer': 807, 'Action': 742...",76,716489,90,8172
Baldur's Gate 3,2023-08-03,17,59.99,2,"Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacri...","Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacri...","Baldur’s Gate 3 is a story-rich, party-based RPG set in the universe of Dungeons &amp; Dragons, ...",NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1086940/header.jpg?t=1740386911,https://baldursgate3.game,...,967,5712,493,0,48021,"{'RPG': 4266, 'Character Customization': 3328, 'Choices Matter': 3300, 'Story Rich': 3235, 'Turn...",96,648637,96,8010
Euro Truck Simulator 2,2012-10-12,0,19.99,98,Just Updated Join your friends and keep on truckin' together in 8 player Convoy multiplayer mode...,"Travel across Europe as king of the road, a trucker who delivers important cargo across impressi...","Travel across Europe as king of the road, a trucker who delivers important cargo across impressi...",“Unexpectedly engrossing. Heed the mockers and you'll miss one of the PC's finest and freshest d...,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/227300/header.jpg?t=1739871676,https://eurotrucksimulator2.com/,...,0,0,0,0,43539,"{'Driving': 12858, 'Transportation': 12635, 'Simulation': 12592, 'Open World': 12511, 'Automobil...",97,641347,96,8950
Red Dead Redemption 2,2019-12-05,17,59.99,0,Ultimate Edition The Red Dead Redemption 2: Ultimate Edition delivers all of the Story Mode cont...,"America, 1899. Arthur Morgan and the Van der Linde gang are outlaws on the run. With federal age...","Winner of over 175 Game of the Year Awards and recipient of over 250 perfect scores, RDR2 is the...",NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/header.jpg?t=1720558643,https://www.rockstargames.com/reddeadredemption2/,...,0,0,0,0,39811,"{'Open World': 3626, 'Story Rich': 2902, 'Western': 2606, 'Adventure': 2512, 'Multiplayer': 2445...",92,640849,95,14567
Destiny 2,2019-10-01,0,0.00,12,Dive into the world of Destiny 2 to explore the mysteries of the solar system and experience res...,Dive into the world of Destiny 2 to explore the mysteries of the solar system and experience res...,Destiny 2 is an action MMO with a single evolving world that you and your friends can join anyti...,NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1085660/header.jpg?t=1738688481,https://www.bungie.net/,...,765,435,473,0,36292,"{'Free to Play': 3512, 'Open World': 3063, 'Looter Shooter': 3018, 'Multiplayer': 3018, 'MMORPG'...",79,621145,69,2909
Phasmophobia,2020-09-18,0,19.99,0,"Join Our Discord Roadmap About the Game Phasmophobia is a 4-player, online co-op, psychological ...","Phasmophobia is a 4-player, online co-op, psychological horror game. You and your team of parano...",Phasmophobia is a 4 player online co-op psychological horror. Paranormal activity is on the rise...,“A truly terrifying psychological online co-op ghost hunting experience” PC Gamer “Phasmophobia ...,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/739630/header.jpg?t=1740090955,http://kineticgames.co.uk/,...,430,927,207,0,20766,"{'Horror': 4333, 'Online Co-Op': 2889, 'Multiplayer': 2625, 'Psychological Horror': 2066, 'Co-op...",96,616505,95,8183
Among Us,2018-11-16,0,2.99,0,Play with 4-15 player online or via local WiFi as you attempt to prepare your spaceship for depa...,Play with 4-15 player online or via local WiFi as you attempt to prepare your spaceship for depa...,An online and local party game of teamwork and betrayal for 4-15 players...in space!,“Made friends from it and probably will lose them all because of it at some point.” 10/10 – BenA...,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/945360/header.jpg?t=1731953093,http://innersloth.com/gameAmongUs.php,...,0,0,0,40,8022,"{'Multiplayer': 1935, 'Social Deduction': 1333, 'Online Co-Op': 1333, 'Space': 1254, 'Survival':...",92,613666,91,2299
Warframe,2013-03-25,17,0.00,13,Warframe 1999 Demo - Available Now Play the Warframe: 1999 Demo today and earn the Protokol Long...,Confront warring factions throughout a sprawling interplanetary system as you follow the guidanc...,Awaken as an unstoppable warrior and battle alongside your friends in this story-driven free-to-...,NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/230410/header.jpg?t=1740594560,http://www.warframe.com,...,0,0,0,0,51688,"{'Free to Play': 15768, 'Action RPG': 15087, 'Looter Shooter': 15076, 'Third-Person Shooter': 14...",87,611151,90,4000

Pronađi sve besplatne igre :D

In [164]:
#df.set_index('price', inplace=True)
df.loc[0.00, 'name']

price
0.0                                 Counter-Strike 2
0.0                              PUBG: BATTLEGROUNDS
0.0                                           Dota 2
0.0                        Grand Theft Auto V Legacy
0.0                                  Team Fortress 2
                           ...
0.0                                     BLASTER LiLO
0.0                                      Party Words
0.0                                    Dan's Odyssey
0.0                        DO_OR_DIE Hunt to Survive
0.0    Might & Magic: Heroes VI - Shades of Darkness
Name: name, Length: 14160, dtype: object

In [ ]:
#Postavlja appid umjesto default indexa
df = pd.read_csv(r"C:\Users\Marko\Desktop\data_folder\steam_games\games_march2025_cleaned.csv", index_col='appid')

,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,header_image,...,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent
appid,,,,,,,,,,,,,,,,,,,,,
730,Counter-Strike 2,2012-08-21,0,0.00,1,"For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by ...","For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by ...","For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by ...",NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/730/header.jpg?t=1729703045,...,879,5174,350,0,1212356,"{'FPS': 90857, 'Shooter': 65397, 'Multiplayer': 62332, 'Competitive': 53359, 'Action': 47512, 'T...",86,8632939,82,96473
578080,PUBG: BATTLEGROUNDS,2017-12-21,0,0.00,0,"LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS for free. Land on strategic locations, loot weapon...","LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS for free. Land on strategic locations, loot weapon...","Play PUBG: BATTLEGROUNDS for free. Land on strategic locations, loot weapons and supplies, and s...",NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/578080/header.jpg?t=1736389084,...,0,0,0,0,616738,"{'Survival': 14838, 'Shooter': 12727, 'Battle Royale': 10877, 'Multiplayer': 10837, 'FPS': 8428,...",59,2513842,68,16720
570,Dota 2,2013-07-09,0,0.00,2,"The most-played game on Steam. Every day, millions of players worldwide enter battle as one of o...","The most-played game on Steam. Every day, millions of players worldwide enter battle as one of o...","Every day, millions of players worldwide enter battle as one of over a hundred Dota heroes. And ...","“A modern multiplayer masterpiece.” 9.5/10 – Destructoid “Once you start to learn its secrets, t...",https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/570/header.jpg?t=1739210483,...,1536,898,892,0,555977,"{'Free to Play': 59933, 'MOBA': 20158, 'Multiplayer': 15359, 'Strategy': 14252, 'e-sports': 1178...",81,2452595,80,29366
271590,Grand Theft Auto V Legacy,2015-04-13,17,0.00,0,"When a young street hustler, a retired bank robber and a terrifying psychopath find themselves e...","When a young street hustler, a retired bank robber and a terrifying psychopath find themselves e...",Grand Theft Auto V for PC offers players the option to explore the award-winning world of Los Sa...,NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/271590/header.jpg?t=1741120008,...,771,7101,74,0,117698,"{'Open World': 32644, 'Action': 23539, 'Multiplayer': 21748, 'Crime': 19422, 'Automobile Sim': 1...",87,1803832,92,17517
359550,Tom Clancy's Rainbow Six® Siege,2015-12-01,17,3.99,9,Edition Comparison Ultimate Edition The Tom Clancy's Rainbow Six® Siege Ultimate Edition include...,“One of the best first-person shooters ever made. 10\10” – GameSpot Tom Clancy's Rainbow Six® Si...,"Tom Clancy's Rainbow Six® Siege is an elite, tactical team-based shooter where superior planning...",NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/359550/header.jpg?t=1741397094,...,682,2434,306,80,89916,"{'FPS': 9831, 'PvP': 9162, 'e-sports': 9072, 'Multiplayer': 9063, 'Tactical': 9056, 'Shooter': 9...",84,1168020,76,12608

In [201]:
df = pd.read_csv(r"C:\Users\Marko\Desktop\data_folder\steam_games\games_march2025_cleaned.csv")

In [ ]:
#Sortiraj abecedno
df.set_index('name',inplace=True)
df.sort_index()

,appid,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,header_image,...,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent
name,,,,,,,,,,,,,,,,,,,,,
! Shakabula *,2556940,2023-10-13,0,14.99,0,Controller_Support ! Shakabula is built with Controller support from the ground up and is curren...,"Be prepared to take on a terrifying South African legend, in this eerie experimental, horror sho...","A South African urban legend called the Shakabula traps you in your house, could it be connected...",NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2556940/header.jpg?t=1697794808,...,0,0,0,0,0,"{'Early Access': 213, 'Action': 193, 'RPG': 187, 'JRPG': 184, 'Shooter': 181, 'Bullet Hell': 178...",-1,-1,-1,-1
! That Bastard Is Trying To Steal Our Gold !,449940,2016-03-03,0,2.99,0,It's a fun puzzle game where you need to steal all gold at each level. Steal gold from the Lerpi...,It's a fun puzzle game where you need to steal all gold at each level. Steal gold from the Lerpi...,Steal gold from the Lerpikon's dungeons! Get rich!,NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/449940/header.jpg?t=1668681370,...,0,391,0,0,0,"{'Puzzle-Platformer': 237, 'Dark Humor': 233, 'Dungeon Crawler': 228, 'Mining': 225, 'Memes': 22...",55,68,-1,-1
! Wild Russia !,1287250,2020-04-28,0,19.99,0,«Wild Russia» is an open-world horror adventure game. Its action takes place in a striking provi...,«Wild Russia» is an open-world horror adventure game. Its action takes place in a striking provi...,«Wild Russia» is an open-world horror adventure game. Its action takes place in a striking provi...,NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1287250/header.jpg?t=1658469423,...,0,0,0,0,0,"{'Adventure': 57, 'Action': 56, 'Casual': 56, 'Horror': 13, 'Post-apocalyptic': 13, 'Atmospheric...",61,62,-1,-1
!AnyWay!,866510,2018-06-06,0,1.99,39,Steam Trading Cards! You can get Steam Trading Cards right now! About the Game Let's Return to O...,Let's Return to Our Past! An unusual world for an unusual person. Attempts of scientists to recr...,Do you like parkour? Dashing retro times? AnyWay! Try yourself on an unsuccessful journey in the...,NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/866510/header.jpg?t=1711176659,...,0,378,0,0,6,"{'Side Scroller': 179, 'Precision Platformer': 173, '2D Platformer': 170, 'Casual': 166, 'Sandbo...",71,495,-1,-1
!LABrpgUP!,870990,2018-06-13,0,0.99,0,LabRpgUp is a unique J-RPG game. Travel through dark labyrinths filled with old guards. Can you ...,LabRpgUp is a unique J-RPG game. Travel through dark labyrinths filled with old guards. Can you ...,LabRpgUp is a unique J-RPG game. Travel through dark labyrinths filled with old guards. Can you ...,NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/870990/header.jpg?t=1528898762,...,0,0,0,0,0,"{'Adventure': 20, 'Indie': 20, 'Casual': 20, 'RPG': 17}",55,18,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
👑万千网友共修仙👑,1843330,2022-10-29,0,2.99,0,游戏玩法： 挂机升级，打怪拿装备，去灵界创建宗门 叮，欢迎玩家进入修仙世界，您是第99999位玩家。 系统提示; 您尚未创建账号，是否立即创建。 是 虹膜确认，指纹确认，开始DNA扫描 叮， ...,游戏玩法： 挂机升级，打怪拿装备，去灵界创建宗门 叮，欢迎玩家进入修仙世界，您是第99999位玩家。 系统提示; 您尚未创建账号，是否立即创建。 是 虹膜确认，指纹确认，开始DNA扫描 叮， ...,文字修仙游戏，成年人喜欢玩的游戏，简单，挂机，不累,NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1843330/header.jpg?t=1667027790,...,0,0,0,0,0,[],-1,-1,-1,-1
🔴 Circles,460250,2017-02-17,0,0.00,0,"Circles is a unique, intuitive puzzle game where everything responds to your mouse. It presents ...","Circles is a unique, intuitive puzzle game where everything responds to your mouse. It presents ...","Circles is an abstract puzzle game that takes your mind off things. No words, no distractions: a...",“Circles is a masterclass in minimalist game design” Killscreen,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/460250/header.jpg?t=1666985953,...,0,0,0,0,0,"{'Experimental': 90, 'Minimalist': 86, 'Abstract': 80, 'Relaxing': 79, 'Puzzle': 75, 'Experience...",90,231,-1,-1
🚀 Human Rocket Person,965340,2018-11-14,0,1.99,0,Join Human Rocket Person on the adventure of a lifetime as he tries to save the universe. Jump y...,Join Human Rocket Person on the adventure of a lifetime as he tries to save the universe. Jump y...,Human Rocket Person is an absurd &amp; fun platformer where you jump &amp; fly through different...,NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/965340/header.jpg?t=1555673536,...,0,0,0,0,0,"{'Indie': 34, 'Action': 31, 'Sexual Content': 28, 'Nudity': 23, 'Simulation': 19, 'Intentionally...",95,44,-1,-1
🧠 OUT OF THE BOX,576960,2018-07-19,17,14.99,0,"Welcome to the Craziest Nightclub In this bouncer simulator you are Warren Baker, the new gateke...","Welcome to the Craziest Nightclub In this bouncer simulator you are Warren Baker, the new gateke...",Dive into a wild story of gangsters and criminals where you decide the fate of the peculiar cust...,“Out of The Box is an underrated game that I feel nobody knows much about” 9 – Bonus Stage “Out ...,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/576960/header.jpg?t=1709573063,...,0,0,0,80,0,"{'Adventure': 377, 'Choose Your Own Adventure': 371, 'Simulation': 367, 'Choices Matter': 363, '...",88,199,-1,-1
𣸩,2639280,2023-12-29,0,1.99,0,游戏性质 《袖珍小说游戏》系列的首部作品，目标是做出篇幅短但精致的小说游戏，玩家将以男主角的视角，结合图像和声音的演出，阅读剧本和体验故事。 制作人员 监督·剧本 箱崎奈绪 示图 海原カイロ ...,游戏性质 《袖珍小说游戏》系列的首部作品，目标是做出篇幅短但精致的小说游戏，玩家将以男主角的视角，结合图像和声音的演出，阅读剧本和体验故事。 制作人员 监督·剧本 箱崎奈绪 示图 海原カイロ ...,《袖珍小说游戏》系列的首部作品，讲述失去了想象能力的作家，和坚持实现梦想的少女之间的故事，玩家将以男主角的视角，结合图像和音乐的演出，阅读剧本并体验和女主角相遇后的经历,NaN,https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2639280/header.jpg?t=1704029803,...,0,0,0,0,0,[],46,15,-1,-1

In [ ]:
#Besplatne igre :D
povoljna_cijena = df['price']==0
free_games=df[povoljna_cijena]

output = pd.DataFrame({'Name': free_games.name, 'About': free_games.short_description})
output.to_csv('free_games.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!

In [7]:
#Indie igre
import pandas as pd
df = pd.read_csv(r"C:\Users\Marko\Desktop\data_folder\steam_games\games_march2025_cleaned.csv")
indie_games = df['tags'].str.contains('Indie', na=False)
df.loc[indie_games]

,appid,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,...,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent
6,105600,Terraria,2011-05-16,0,9.99,2,"Dig, Fight, Explore, Build: The very world is ...","Dig, Fight, Explore, Build: The very world is ...","Dig, fight, explore, build! Nothing is impossi...",NaN,...,0,0,0,0,30516,"{'Open World Survival Craft': 16365, 'Sandbox'...",97,1102434,96,8860
7,252490,Rust,2018-02-08,0,39.99,4,The only aim in Rust is to survive. Everything...,The only aim in Rust is to survive. Everything...,The only aim in Rust is to survive. Everything...,"“Rust is one of the cruelest games on Steam, a...",...,836,3675,231,0,200902,"{'Survival': 18592, 'Crafting': 11822, 'Multip...",87,993856,87,14960
8,4000,Garry's Mod,2006-11-29,0,5.99,0,Garry's Mod is a physics sandbox. There aren't...,Garry's Mod is a physics sandbox. There aren't...,Garry's Mod is a physics sandbox. There aren't...,“It brings back the silly glee of unbridled ex...,...,100,1173,136,40,32384,"{'Sandbox': 18706, 'Moddable': 14479, 'Multipl...",96,985010,96,8277
13,413150,Stardew Valley,2016-02-26,0,14.99,1,Stardew Valley is an open-ended country-life R...,Stardew Valley is an open-ended country-life R...,You've inherited your grandfather's old farm p...,"“Far more than just a farming game, this one-m...",...,158,2053,87,0,67309,"{'Farming Sim': 7706, 'Pixel Graphics': 7169, ...",98,733626,98,8622
17,227300,Euro Truck Simulator 2,2012-10-12,0,19.99,98,Just Updated Join your friends and keep on tru...,"Travel across Europe as king of the road, a tr...","Travel across Europe as king of the road, a tr...",“Unexpectedly engrossing. Heed the mockers and...,...,0,0,0,0,43539,"{'Driving': 12858, 'Transportation': 12635, 'S...",97,641347,96,8950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89612,801660,Swapper Tiles,2018-05-07,0,0.99,0,Swapper Tiles is a first person puzzle game wh...,Swapper Tiles is a first person puzzle game wh...,Swapper Tiles is a First Person Puzzle game wh...,NaN,...,0,0,0,0,0,"{'Strategy': 31, 'Indie': 31, 'Early Access': ...",-1,-1,-1,-1
89613,2115110,Outrun Them,2024-02-29,0,3.99,0,The name of the game is literally the game. Ou...,The name of the game is literally the game. Ou...,It's all in the name.. outrun them.,NaN,...,0,0,0,0,0,"{'2D Platformer': 91, 'Runner': 85, 'Platforme...",-1,-1,-1,-1
89614,1174200,Lands of Pharaoh: Episode 1,2020-01-07,0,10.00,0,Join Our Discord Channel About the Game Briefl...,Briefly: Lands of Pharaoh is a third person vi...,Lands of Pharaoh is a multi-camera-angle based...,NaN,...,0,0,0,0,0,"{'Action': 43, 'Adventure': 41, 'Indie': 41, '...",-1,-1,-1,-1
89615,1160190,Player One,2019-10-10,0,1.99,0,Player One is a new 3D game where you take con...,Player One is a new 3D game where you take con...,"3D Game, Thirdperson Platformer",NaN,...,0,0,0,0,0,"{'Indie': 31, 'Early Access': 21}",-1,-1,-1,-1
89617,763730,Ragtag Adventurers,2018-03-01,0,9.99,0,Ragtag Adventurers is a Boss Rush game that pi...,Ragtag Adventurers is a Boss Rush game that pi...,Ragtag Adventurers is a boss rush game that pi...,NaN,...,0,0,0,0,0,"{'Action': 22, 'Indie': 21}",-1,-1,-1,-1

In [8]:
#Multiplayer igre
indie_games = df['tags'].str.contains('Multiplayer', na=False)
df.loc[indie_games]

,appid,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,...,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent
0,730,Counter-Strike 2,2012-08-21,0,0.00,1,"For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...",NaN,...,879,5174,350,0,1212356,"{'FPS': 90857, 'Shooter': 65397, 'Multiplayer'...",86,8632939,82,96473
1,578080,PUBG: BATTLEGROUNDS,2017-12-21,0,0.00,0,"LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...","LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...",Play PUBG: BATTLEGROUNDS for free. Land on str...,NaN,...,0,0,0,0,616738,"{'Survival': 14838, 'Shooter': 12727, 'Battle ...",59,2513842,68,16720
2,570,Dota 2,2013-07-09,0,0.00,2,"The most-played game on Steam. Every day, mill...","The most-played game on Steam. Every day, mill...","Every day, millions of players worldwide enter...",“A modern multiplayer masterpiece.” 9.5/10 – D...,...,1536,898,892,0,555977,"{'Free to Play': 59933, 'MOBA': 20158, 'Multip...",81,2452595,80,29366
3,271590,Grand Theft Auto V Legacy,2015-04-13,17,0.00,0,"When a young street hustler, a retired bank ro...","When a young street hustler, a retired bank ro...",Grand Theft Auto V for PC offers players the o...,NaN,...,771,7101,74,0,117698,"{'Open World': 32644, 'Action': 23539, 'Multip...",87,1803832,92,17517
4,359550,Tom Clancy's Rainbow Six® Siege,2015-12-01,17,3.99,9,Edition Comparison Ultimate Edition The Tom Cl...,“One of the best first-person shooters ever ma...,"Tom Clancy's Rainbow Six® Siege is an elite, t...",NaN,...,682,2434,306,80,89916,"{'FPS': 9831, 'PvP': 9162, 'e-sports': 9072, '...",84,1168020,76,12608
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89588,3245910,Baratrum,2024-12-11,0,3.99,0,"You've woken up in limbo, somewhere between he...","You've woken up in limbo, somewhere between he...",Baratrum is an arcade horror game where every ...,NaN,...,0,0,0,0,0,"{'Top-Down Shooter': 99, 'Dungeon Crawler': 93...",-1,-1,-1,-1
89599,2935280,Zector 7,2024-10-25,0,9.99,0,Zector 7 is a sci-fi zombie survival game set ...,Zector 7 is a sci-fi zombie survival game set ...,"Craft, Build and Fight alongside your friends ...",NaN,...,0,0,0,0,0,"{'Survival': 196, 'Zombies': 190, 'Open World'...",-1,-1,-1,-1
89601,1527230,UC KART,2021-03-12,0,0.99,0,UC KART is a racing game for 1 to 4 players. T...,UC KART is a racing game for 1 to 4 players. T...,UC KART is a racing game. There is HP in the c...,NaN,...,0,0,0,0,0,"{'Racing': 63, '3D': 37, 'PvP': 33, 'Multiplay...",-1,-1,-1,-1
89608,3065390,Caribbean Pirates,2024-07-24,0,3.99,0,Caribbean Pirates is a board game that immerse...,Caribbean Pirates is a board game that immerse...,A tactical board game about the battles of sai...,NaN,...,0,0,0,0,0,"{'Pirates': 252, 'Naval Combat': 246, 'Board G...",-1,-1,-1,-1
89616,3380340,DragonRoad,2025-01-25,0,29.99,0,"This is an open world game on 3D, also a m...","This is an open world game on 3D, also a m...","This is an open world game on 3D, Also a missi...",NaN,...,0,0,0,0,0,"{'RPG': 117, 'Action-Adventure': 111, 'Strateg...",-1,-1,-1,-1

In [ ]:
#Igre koje su "free-to-play"

free_to_play = df['tags'].str.contains('Free to Play', na=False)
df.loc[free_to_play]

,appid,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,...,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent
2,570,Dota 2,2013-07-09,0,0.00,2,"The most-played game on Steam. Every day, mill...","The most-played game on Steam. Every day, mill...","Every day, millions of players worldwide enter...",“A modern multiplayer masterpiece.” 9.5/10 – D...,...,1536,898,892,0,555977,"{'Free to Play': 59933, 'MOBA': 20158, 'Multip...",81,2452595,80,29366
5,440,Team Fortress 2,2007-10-10,0,0.00,1,'The most fun you can have online' - PC Gamer ...,'The most fun you can have online' - PC Gamer ...,Nine distinct classes provide a broad range of...,NaN,...,0,0,0,0,50817,"{'Free to Play': 62868, 'Hero Shooter': 61020,...",89,1146642,93,8172
9,1172470,Apex Legends™,2020-11-04,0,0.00,0,Apex Legends: Takeover About the Game Conquer ...,"Conquer with character in Apex Legends, a free...","Apex Legends is the award-winning, free-to-pla...",“The champion of Battle Royales.” 9/10 – GameS...,...,548,667,211,0,151844,"{'Free to Play': 2170, 'Battle Royale': 1483, ...",67,983230,53,7054
19,1085660,Destiny 2,2019-10-01,0,0.00,12,Dive into the world of Destiny 2 to explore th...,Dive into the world of Destiny 2 to explore th...,Destiny 2 is an action MMO with a single evolv...,NaN,...,765,435,473,0,36292,"{'Free to Play': 3512, 'Open World': 3063, 'Lo...",79,621145,69,2909
22,230410,Warframe,2013-03-25,17,0.00,13,Warframe 1999 Demo - Available Now Play the Wa...,Confront warring factions throughout a sprawli...,Awaken as an unstoppable warrior and battle al...,NaN,...,0,0,0,0,51688,"{'Free to Play': 15768, 'Action RPG': 15087, '...",87,611151,90,4000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88517,3071270,Linum,2024-07-19,0,0.00,0,Linum is a puzzle game that will test your log...,Linum is a puzzle game that will test your log...,Difficult puzzles that will test your logical ...,NaN,...,0,0,0,0,0,"{'Indie': 55, 'Logic': 47, 'Puzzle': 41, 'Diff...",-1,-1,-1,-1
88969,937160,BRING IT DOWN!,2019-10-22,0,6.99,0,[BRING IT DOWN! Requires a VR Headset to play....,[BRING IT DOWN! Requires a VR Headset to play....,Experience the joy of razing buildings with ex...,NaN,...,0,0,0,0,0,"{'FPS': 115, 'Sandbox': 109, 'Physics': 106, '...",-1,-1,-1,-1
89012,2620950,UnderOneRoof,2023-10-15,0,0.00,0,(Using translator) This short game has fewer i...,(Using translator) This short game has fewer i...,This is a 10 minute short story game adapted f...,NaN,...,0,0,0,0,0,"{'RPG': 67, 'Singleplayer': 42, 'Mystery': 39,...",-1,-1,-1,-1
89014,773850,WT2,2020-01-02,0,0.00,0,"Destroy, smash and blast your way to victory! ...","Destroy, smash and blast your way to victory! ...","Destroy, smash and blast your way to victory. ...",NaN,...,0,0,0,0,0,"{'Free to Play': 43, 'Indie': 42, 'Action': 41...",-1,-1,-1,-1
89510,2227830,DO_OR_DIE Hunt to Survive,2023-01-03,0,0.00,0,“DO OR DIE – Hunt To Survive” presents an acti...,“DO OR DIE – Hunt To Survive” presents an acti...,The concept of 'DO OR DIE – Hunt To Survive' r...,NaN,...,0,0,0,0,0,"{'Action': 66, 'Shooter': 40, '3D': 37, 'Third...",-1,-1,-1,-1

In [ ]:
povoljna_cijena = df['price']==0
free_games=df[povoljna_cijena]

besplatna_reklama = df['tags'].str.contains('Free to Play', na=False)
free_to_play=df[besplatna_reklama]

In [ ]:
#Provjera što pokazuju tagovi i cijene - većina igri je besplatna jer je možda neka promocija i/ili ima demo -> iščitano i pogledano u tablici
free_games
free_to_play

,appid,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,...,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent
0,730,Counter-Strike 2,2012-08-21,0,0.0,1,"For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...","For over two decades, Counter-Strike has offer...",NaN,...,879,5174,350,0,1212356,"{'FPS': 90857, 'Shooter': 65397, 'Multiplayer'...",86,8632939,82,96473
1,578080,PUBG: BATTLEGROUNDS,2017-12-21,0,0.0,0,"LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...","LAND, LOOT, SURVIVE! Play PUBG: BATTLEGROUNDS ...",Play PUBG: BATTLEGROUNDS for free. Land on str...,NaN,...,0,0,0,0,616738,"{'Survival': 14838, 'Shooter': 12727, 'Battle ...",59,2513842,68,16720
2,570,Dota 2,2013-07-09,0,0.0,2,"The most-played game on Steam. Every day, mill...","The most-played game on Steam. Every day, mill...","Every day, millions of players worldwide enter...",“A modern multiplayer masterpiece.” 9.5/10 – D...,...,1536,898,892,0,555977,"{'Free to Play': 59933, 'MOBA': 20158, 'Multip...",81,2452595,80,29366
3,271590,Grand Theft Auto V Legacy,2015-04-13,17,0.0,0,"When a young street hustler, a retired bank ro...","When a young street hustler, a retired bank ro...",Grand Theft Auto V for PC offers players the o...,NaN,...,771,7101,74,0,117698,"{'Open World': 32644, 'Action': 23539, 'Multip...",87,1803832,92,17517
5,440,Team Fortress 2,2007-10-10,0,0.0,1,'The most fun you can have online' - PC Gamer ...,'The most fun you can have online' - PC Gamer ...,Nine distinct classes provide a broad range of...,NaN,...,0,0,0,0,50817,"{'Free to Play': 62868, 'Hero Shooter': 61020,...",89,1146642,93,8172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89423,999750,BLASTER LiLO,2018-12-28,0,0.0,0,Blast your way through an endless flow of enem...,Blast your way through an endless flow of enem...,Blast through an endless horde of enemies in t...,NaN,...,0,0,0,0,0,"{'Action': 21, ""Shoot 'Em Up"": 12, 'Multiplaye...",-1,-1,-1,-1
89434,1992530,Party Words,2022-12-06,0,0.0,3,Party Words is a.... party word game. It combi...,Party Words is a.... party word game. It combi...,Party Words is a word party game with a bunch ...,NaN,...,0,0,0,0,0,"{'Casual': 60, 'Word Game': 52, 'Party Game': ...",-1,-1,-1,-1
89450,2182170,Dan's Odyssey,2022-11-03,0,0.0,0,Dan's odyssey is an arcade like arena top down...,Dan's odyssey is an arcade like arena top down...,An arcade arena top down shooter. fast paced a...,NaN,...,0,0,0,0,0,"{'Action': 222, 'Casual': 217, 'Top-Down': 212...",-1,-1,-1,-1
89510,2227830,DO_OR_DIE Hunt to Survive,2023-01-03,0,0.0,0,“DO OR DIE – Hunt To Survive” presents an acti...,“DO OR DIE – Hunt To Survive” presents an acti...,The concept of 'DO OR DIE – Hunt To Survive' r...,NaN,...,0,0,0,0,0,"{'Action': 66, 'Shooter': 40, '3D': 37, 'Third...",-1,-1,-1,-1
89574,229790,Might & Magic: Heroes VI - Shades of Darkness,2013-05-02,0,0.0,0,A century after the tragic events of Might &am...,A century after the tragic events of Might &am...,A century after the tragic events of Might &am...,NaN,...,0,0,0,0,0,"{'Strategy': 60, 'RPG': 46, 'Turn-Based Strate...",-1,-1,-1,-1

In [32]:
df.apply(len)

appid                       89618
name                        89618
release_date                89618
required_age                89618
price                       89618
dlc_count                   89618
detailed_description        89618
about_the_game              89618
short_description           89618
reviews                     89618
header_image                89618
website                     89618
support_url                 89618
support_email               89618
windows                     89618
mac                         89618
linux                       89618
metacritic_score            89618
metacritic_url              89618
achievements                89618
recommendations             89618
notes                       89618
supported_languages         89618
full_audio_languages        89618
packages                    89618
developers                  89618
publishers                  89618
categories                  89618
genres                      89618
screenshots                 89618
movies                      89618
user_score                  89618
score_rank                  89618
positive                    89618
negative                    89618
estimated_owners            89618
average_playtime_forever    89618
average_playtime_2weeks     89618
median_playtime_forever     89618
median_playtime_2weeks      89618
discount                    89618
peak_ccu                    89618
tags                        89618
pct_pos_total               89618
num_reviews_total           89618
pct_pos_recent              89618
num_reviews_recent          89618
dtype: int64

In [33]:
df.sort_values('price')

,appid,name,release_date,required_age,price,dlc_count,detailed_description,about_the_game,short_description,reviews,...,average_playtime_2weeks,median_playtime_forever,median_playtime_2weeks,discount,peak_ccu,tags,pct_pos_total,num_reviews_total,pct_pos_recent,num_reviews_recent
43787,3361890,V-Shift,2025-01-04,0,0.00,0,"V-Shift is a high-intensity , fast paced battl...","V-Shift is a high-intensity , fast paced battl...","V-Shift is a high-intensity, fast-paced, battl...",NaN,...,0,0,0,0,0,[],93,16,-1,-1
43781,718960,The Flesh God,2017-11-02,0,0.00,0,The Flesh God is a hardcore action platformer ...,The Flesh God is a hardcore action platformer ...,The Flesh God is a tough action platformer whe...,NaN,...,0,0,0,0,0,"{'Action': 21, 'Indie': 21, 'Free to Play': 20...",81,16,-1,-1
79,433850,Z1 Battle Royale,2018-02-28,0,0.00,0,"Z1 Battle Royale is a Free to Play, fast-paced...","Z1 Battle Royale is a Free to Play, fast-paced...","Z1 Battle Royale is a Free to Play, fast-paced...","“With a variety of game modes, H1Z1 offers a s...",...,0,108,0,0,974,"{'Survival': 2852, 'Massively Multiplayer': 16...",55,204340,61,76
77,698780,Doki Doki Literature Club!,2017-10-06,0,0.00,1,"Hi, Monika here! Welcome to the Literature Clu...","Hi, Monika here! Welcome to the Literature Clu...",The Literature Club is full of cute girls! Wil...,NaN,...,0,0,0,0,579,"{'Psychological Horror': 8857, 'Visual Novel':...",96,208735,95,1419
76,700330,SCP: Secret Laboratory,2017-12-29,0,0.00,0,Deep within one of the SCP Foundation’s emerge...,Deep within one of the SCP Foundation’s emerge...,"Deep within a secure underground facility, a s...",NaN,...,121,85,121,0,6916,"{'Free to Play': 2195, 'Multiplayer': 1856, 'H...",91,209939,89,1889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72266,253670,Aartform Curvy 3D 3.0,2013-11-12,0,299.90,0,Curvy 3D 5 Curvy 3D 5 is out now! \\ Aartform ...,Curvy 3D 3.0 is an innovative sculpting progra...,Curvy 3D 3.0 is an innovative sculpting progra...,NaN,...,0,0,0,0,0,{'Animation & Modeling': 24},-1,-1,-1,-1
84664,3013840,True Love,2024-06-27,0,500.00,0,This game created out of pure sadness. I have ...,This game created out of pure sadness. I have ...,If you are looking for the True Love... Here y...,NaN,...,0,0,0,0,0,"{'Casual': 413, 'Action-Adventure': 387, 'Visu...",-1,-1,-1,-1
64631,1200520,Ascent Free-Roaming VR Experience,2019-12-27,0,999.00,0,The Ascent is a Free-Roaming highly immersive ...,The Ascent is a Free-Roaming highly immersive ...,A premium highly-immersive VR experience devel...,NaN,...,0,0,0,0,0,"{'Action': 95, 'Hentai': 42, 'Nudity': 37, 'Se...",-1,-1,-1,-1
81168,2499620,The Leverage Game,2023-08-25,0,999.98,0,The Leverage Game is a board game in which pla...,The Leverage Game is a board game in which pla...,"You can learn realistic, world-class managemen...",NaN,...,0,0,0,0,0,"{'Board Game': 47, 'Turn-Based Tactics': 42, '...",-1,-1,-1,-1
60133,2504210,The Leverage Game Business Edition,2023-08-26,0,999.98,0,The Leverage Game is a board game in which pla...,The Leverage Game is a board game in which pla...,"You can learn realistic, world-class managemen...",NaN,...,0,0,0,0,0,[],-1,-1,-1,-1

In [ ]:
#